name: DESTROY · AWS

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Escribe DESTRUIR para confirmar'
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    uses: gpalaciosvx3/gpalacios-pipelines/.github/workflows/aws-cdk-destroy.yml@v1
    with:
      confirmation: ${{ inputs.confirmation }}
